# Site settings
title: Utrecht Java User Group
email: utrechtjug@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The official Java User Group of Utrecht Hollande
  Events, speakers and other activities of Utrecht JUG.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jug.mk" # the base hostname & protocol for your site
twitter_username: utrechtjug
github_username:  utrechtjug
collections:
  event:
    output: true
  gallery:
    output: true
defaults:
  - scope:
      path: ""
      type: event
    values:
      layout: events
      icon: beer
  - scope:
      path: ""
      type: gallery
    values:
      layout: gallery
      icon: photo
# Build settings
markdown: kramdown
